fastapi:
  image_name: fastapi-app:v1.0.3
  replicas: 1
  prometheus_scrape: true
  prometheus_port: 8000
  prometheus_path: /metrics
  ingress:
    enabled: true
    host: api.tatsumaki.local
    className: traefik
    paths:
      - /users
      - /posts

postgres:
  pvcName: postgres-pvc
  storage: 1Gi
  replicas: 1
  user: postgres
  password: postgres
  database: wiki

grafana:
  admin_user: admin
  admin_password: admin
  namespace: default
  serviceName: grafana
  servicePort: 3000
  ingress:
    enabled: true
    host: grafana.tatsumaki.local
    className: traefik
    paths:
      - /grafana/d/creation-dashboard-678/creation
      - /grafana

prometheus:
  scrape_interval: 15s   # must be present
