{{- if .Values.fastapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress-rule
  labels:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.fastapi.ingress.className }}"
spec:
  rules:
  - host: {{ .Values.fastapi.ingress.host }}
    http:
      paths:
      {{- range .Values.fastapi.ingress.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: fastapi-app-service
            port:
              number: {{ $.Values.fastapi.prometheus_port }}
      {{- end }}
{{- end }}
