apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      # Job to scrape Kubernetes components
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node

      # Job to scrape your FastAPI application
      - job_name: 'fastapi-app-metrics'
        # Service discovery role targets the FastAPI Service
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          # Keep only the target service: fastapi-app-service
          - source_labels: [__meta_kubernetes_service_name]
            regex: fastapi-app-service
            action: keep
          # Set the scrape port to the application's exposed port (8000)
          - source_labels: [__address__]
            target_label: __address__
            regex: (.+):\d+
            replacement: $1:8000
          # Define the metrics path
          - target_label: __metrics_path__
            replacement: /metrics
